version: '3.9'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres-auth:
    image: postgres:alpine
    container_name: postgres-auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_auth
      POSTGRES_PASSWORD: password_auth
      POSTGRES_DB: auth_db
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data

  postgres-core:
    image: postgres:alpine
    container_name: postgres-core
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user_core
      POSTGRES_PASSWORD: password_core
      POSTGRES_DB: core_db
    volumes:
      - postgres-core-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-auth-data:
  postgres-core-data:
